"""Bundled labeled seed corpus for the general-news topic classifier.

This is the *training data* for a small, dependency-light supervised model (see
``news_topics.py``). It is deliberately modest in size: the goal is an honest,
reproducible topic signal for general news headlines - not a production-scale
corpus. Every label here is a general newsroom desk (not the exam/NEET domain
categories, which stay rule-based in ``domain_config``).

Deterministic by construction: no random ordering, plain (text, label) tuples.
"""
from __future__ import annotations

from typing import List, Tuple

# The general news topic taxonomy the model predicts into.
TAXONOMY: List[str] = [
    "World",
    "Politics",
    "Business",
    "Technology",
    "Sports",
    "Health",
    "Science",
    "Entertainment",
    "Climate",
    "Crime",
    "Education",
]

# Fallback label when the text is out-of-vocabulary or too uncertain.
FALLBACK_LABEL = "Other"

SEED_CORPUS: List[Tuple[str, str]] = [
    # ---- World -----------------------------------------------------------
    ("UN Security Council meets in emergency session over the border conflict", "World"),
    ("Foreign ministers hold a summit to negotiate a ceasefire agreement", "World"),
    ("Sanctions eased as two nations restore diplomatic ties", "World"),
    ("Refugee crisis deepens along the disputed international border", "World"),
    ("World leaders gather for the annual diplomacy and security summit", "World"),
    ("Embassy issues advisory for citizens amid rising tensions abroad", "World"),
    ("Peace talks resume between rival nations after months of war", "World"),
    ("International observers monitor the overseas general election", "World"),
    ("Trade deal signed between regional blocs at a multilateral summit", "World"),
    ("Humanitarian aid convoy reaches the conflict-stricken region", "World"),
    ("Prime minister visits an allied nation to strengthen the defence partnership", "World"),
    ("Diplomatic row erupts over the contested maritime boundary", "World"),
    ("Election results abroad spark celebrations and protests", "World"),
    ("Global leaders condemn the attack in the cross-border incident", "World"),
    ("New treaty on migration signed by dozens of countries", "World"),
    ("Hostilities flare in the disputed territory despite a UN resolution", "World"),
    ("Cross-border shelling kills civilians in the contested border village", "World"),
    ("Aid agencies warn of famine as the civil war displaces thousands", "World"),
    ("Historic peace agreement ends a decade-long regional standoff", "World"),
    ("Newly released footage shows troops massing near the frontier", "World"),
    ("International court issues an arrest warrant related to the conflict", "World"),
    ("Ceasefire collapses as both sides accuse each other of violations", "World"),
    ("Millions flee to neighbouring countries in the worst refugee surge", "World"),
    ("Foreign secretary hosts talks to de-escalate the diplomatic crisis", "World"),
    ("Maritime dispute escalates after naval vessels face off at sea", "World"),
    ("Election commission abroad announces results amid fraud allegations", "World"),
    ("Human-rights watchdog documents abuses in the conflict zone", "World"),
    ("Neighbouring states form an alliance in response to the crisis", "World"),
    ("Airstrikes hit a convoy in the disputed northern province", "World"),
    ("Sanctions package approved over the annexation referendum", "World"),
    ("Summit communiqué reaffirms commitment to territorial integrity", "World"),
    ("Kidnap victim released after months of cross-border mediation", "World"),
    ("Twin blasts at a foreign market are claimed by an armed group", "World"),
    ("Observers call the coastal nation's vote free and fair", "World"),
    ("Government apologises for the colonial-era massacre abroad", "World"),
    ("Rebuild effort funded by international donors after the quake", "World"),
    # ---- Politics --------------------------------------------------------
    ("Parliament passes the contentious reform bill after a long debate", "Politics"),
    ("Opposition stages a walkout over government policy in the assembly", "Politics"),
    ("Chief minister announces a cabinet reshuffle and new ministries", "Politics"),
    ("Election commission sets the schedule for the state assembly polls", "Politics"),
    ("Ruling party wins the municipal corporation elections by a wide margin", "Politics"),
    ("Minister defends the budget cut in a heated parliamentary session", "Politics"),
    ("A vote of no confidence is moved against the state government", "Politics"),
    ("Party high command finalises the candidate list for the upcoming polls", "Politics"),
    ("Government unveils a new tax policy drawing sharp criticism", "Politics"),
    ("Legislature debates the controversial citizenship amendment", "Politics"),
    ("Coalition allies clash over the allocation of key portfolios", "Politics"),
    ("Opposition leader promises a welfare scheme ahead of the general election", "Politics"),
    ("Assembly passes a resolution urging the centre to revise the farm law", "Politics"),
    ("Political analyst predicts a swing in urban voting patterns", "Politics"),
    ("A new party is formed ahead of the election on an anti-corruption agenda", "Politics"),
    ("Senators question the nominee at a confirmation hearing", "Politics"),
    ("Cabinet approves the controversial land-acquisition ordinance", "Politics"),
    ("Speaker adjourns the house sine die after the shouting match", "Politics"),
    ("Party announces its manifesto with welfare and farm promises", "Politics"),
    ("By-election loss prompts soul-searching inside the ruling camp", "Politics"),
    ("Ethics panel probes the legislator's undisclosed assets", "Politics"),
    ("Governor and chief minister locked in a constitutional standoff", "Politics"),
    ("Parliamentary committee summons officials over the scam", "Politics"),
    ("New delimitation commission redraws the constituency map", "Politics"),
    ("Protesters gather outside the assembly against the new law", "Politics"),
    ("Deputy chief minister resigns, triggering a coalition crisis", "Politics"),
    ("Election rallies begin as parties court rural voters", "Politics"),
    ("Floor test scheduled after the governor calls a trust vote", "Politics"),
    ("Anti-defection notice issued to the rebel legislators", "Politics"),
    ("Minister resigns following the sting-operation exposé", "Politics"),
    ("Legislature passes the delayed farm-loan waiver bill", "Politics"),
    ("Local-body polls see a surge in women candidates", "Politics"),
    ("Opposition forms an alliance ahead of the national polls", "Politics"),
    ("Party splits as the faction leader announces a new outfit", "Politics"),
    ("Poll panel cautions leaders over the model-code violation", "Politics"),
    ("Whip issued to members before the crucial division vote", "Politics"),
    # ---- Business --------------------------------------------------------
    ("Stock market hits a record high as investor sentiment improves", "Business"),
    ("Central bank holds interest rates steady amid inflation fears", "Business"),
    ("Company reports quarterly earnings that beat analyst expectations", "Business"),
    ("Rupee strengthens against the dollar on strong foreign inflows", "Business"),
    ("Merger of the two giants creates the largest player in the industry", "Business"),
    ("Unemployment falls as the economy adds jobs in the new quarter", "Business"),
    ("Government raises the GDP growth forecast for the fiscal year", "Business"),
    ("Oil prices surge after supply cuts by exporting nations", "Business"),
    ("Startup raises fresh funding in a Series B valuation round", "Business"),
    ("Retail inflation cools for the third consecutive month", "Business"),
    ("IT major announces layoffs amid a global demand slowdown", "Business"),
    ("Bond yields climb as markets brace for a rate hike", "Business"),
    ("Budget announces tax relief for middle-income households", "Business"),
    ("Factory output rebounds, signalling a manufacturing recovery", "Business"),
    ("Bank cuts lending rates to boost business investment", "Business"),
    ("Gold price hits an all-time high on safe-haven demand", "Business"),
    ("Factory activity contracts for a second straight month", "Business"),
    ("Currency slide prompts the central bank to intervene", "Business"),
    ("E-commerce major posts its first profitable quarter", "Business"),
    ("Auto sales rebound on festive-season demand", "Business"),
    ("Markets tumble after the global tariff announcement", "Business"),
    ("Refiner raises fuel prices for the first time this year", "Business"),
    ("Pharma exporter wins regulatory clearance for a new drug", "Business"),
    ("Private bank raises capital through a rights issue", "Business"),
    ("Freight rates ease as container shipping normalises", "Business"),
    ("Retail giant opens its first store in the region", "Business"),
    ("Growth outlook cut by the rating agency on weak demand", "Business"),
    ("Ad-spends recover as media buyers regain confidence", "Business"),
    ("Cement makers seek a price hike on rising input costs", "Business"),
    ("Software exporter guides for double-digit revenue growth", "Business"),
    ("Grain exports slow as the country imposes shipping curbs", "Business"),
    ("Infrastructure firms win highway bids at a record value", "Business"),
    ("Consumer-confidence index slips on inflation worries", "Business"),
    ("Distiller ties up a raw-material deal to cut costs", "Business"),
    ("IPO opens for subscription and is booked several times over", "Business"),
    ("Services output expands at the fastest pace in a year", "Business"),
    # ---- Technology ------------------------------------------------------
    ("Tech giant unveils a new AI-powered smartphone at its launch event", "Technology"),
    ("Chipmaker reveals a next-generation semiconductor at its fab", "Technology"),
    ("Software company rolls out a major operating system update", "Technology"),
    ("Artificial intelligence model sets a new benchmark in research", "Technology"),
    ("Cybersecurity breach exposes millions of user accounts", "Technology"),
    ("Startup launches a cloud platform for enterprise developers", "Technology"),
    ("New data centre will boost computing and AI infrastructure", "Technology"),
    ("Social media app introduces encryption for private messaging", "Technology"),
    ("Robotics firm demonstrates an autonomous warehouse system", "Technology"),
    ("Tech regulation bill targets big-data privacy practices", "Technology"),
    ("Foldable display impresses early adopters in the latest gadget review", "Technology"),
    ("Open-source community releases an update to a popular framework", "Technology"),
    ("Quantum computing breakthrough reported by a research lab", "Technology"),
    ("Electric-vehicle maker debuts a self-driving software feature", "Technology"),
    ("Internet outage disrupts streaming and payment services", "Technology"),
    ("Semiconductor demand outpaces global supply this quarter", "Technology"),
    ("Messaging platform adds a paid verification badge", "Technology"),
    ("Chip export controls hit the semiconductor supplier", "Technology"),
    ("Phone maker shifts production to a new factory", "Technology"),
    ("Data-protection authority fines the social network", "Technology"),
    ("Search engine rolls out AI-generated answer summaries", "Technology"),
    ("Wearable startup unveils a health-tracking smart ring", "Technology"),
    ("Enterprise software vendor acquires a security firm", "Technology"),
    ("Gaming-console launch sells out all pre-orders", "Technology"),
    ("Cloud provider opens a local availability zone", "Technology"),
    ("Browser update patches a critical zero-day flaw", "Technology"),
    ("EV startup hits a production milestone at its plant", "Technology"),
    ("E-commerce app pilots drone package delivery", "Technology"),
    ("Fintech adds real-time international payment rails", "Technology"),
    ("Robotics lab demos a dexterous warehouse arm", "Technology"),
    ("Streaming service introduces an ad-supported tier", "Technology"),
    ("Satellite internet begins consumer beta access", "Technology"),
    ("AI-chip startup raises a large funding round", "Technology"),
    ("Payment app suffers a temporary outage for users", "Technology"),
    ("Operating-system update brings on-device translation", "Technology"),
    ("Developer conference announces a new programming SDK", "Technology"),
    # ---- Sports ----------------------------------------------------------
    ("Team clinches the series victory with a last-over six in the final match", "Sports"),
    ("Bowler takes five wickets to lead the side to an innings win", "Sports"),
    ("Striker scores a hat-trick as the football club dominates the derby", "Sports"),
    ("Athlete breaks the national record in the 100m sprint at the championships", "Sports"),
    ("Coach names the squad for the upcoming World Cup tournament", "Sports"),
    ("Tennis star reaches the semi-final after a grueling five-set battle", "Sports"),
    ("League announces the new season schedule and fixture list", "Sports"),
    ("Champion retires after a legendary career spanning two decades", "Sports"),
    ("Underdog team upsets the top seed in the knockout playoff", "Sports"),
    ("Transfer window closes as the striker joins for a record fee", "Sports"),
    ("Batter reaches a century in the decisive test match innings", "Sports"),
    ("Olympic committee confirms the host city for the next summer games", "Sports"),
    ("Defender's late goal secures a draw in the title race", "Sports"),
    ("Franchise appoints a new head coach ahead of training camp", "Sports"),
    ("Captain lifts the trophy after a dramatic final victory", "Sports"),
    ("Doping ban upheld for the sprinter by the athletics body", "Sports"),
    ("All-rounder's fifty and three wickets win the thriller", "Sports"),
    ("Full-back's header wins the derby in injury time", "Sports"),
    ("Sprinter misses the final by a hundredth of a second", "Sports"),
    ("Franchise retains its captain ahead of the player auction", "Sports"),
    ("Unbeaten run ends after a goalless draw away", "Sports"),
    ("Grand Slam seed crashes out in the opening round", "Sports"),
    ("Rookie signs a multi-year contract with the club", "Sports"),
    ("Host nation unveils the stadium for the tournament", "Sports"),
    ("Video review awards the decisive penalty", "Sports"),
    ("Middle-order collapse hands the series to the visitors", "Sports"),
    ("Marathon record falls on a cool morning course", "Sports"),
    ("Coach rotates the squad for the midweek cup tie", "Sports"),
    ("Swimmer takes gold in the 200m freestyle final", "Sports"),
    ("Injury sidelines the striker for six weeks", "Sports"),
    ("Rider clinches the title in the season finale", "Sports"),
    ("Team qualifies for the continental championship", "Sports"),
    ("Bowling action suspended for an illegal run-up", "Sports"),
    ("Night match draws the season's biggest crowd", "Sports"),
    ("Veteran goalkeeper wins a record cap", "Sports"),
    ("Home side stages a dramatic comeback to win the tie", "Sports"),
    # ---- Health ----------------------------------------------------------
    ("New vaccine shows promise in late-stage clinical trials", "Health"),
    ("Hospitals report a surge in seasonal flu and respiratory illness", "Health"),
    ("Health ministry launches a nationwide vaccination drive", "Health"),
    ("Doctor warns about rising cases of lifestyle diseases", "Health"),
    ("WHO declares the end of the outbreak after containment measures", "Health"),
    ("Study links sleep deprivation to heart-disease risk", "Health"),
    ("Mental-health awareness campaign targets youth wellbeing", "Health"),
    ("Hospital introduces an advanced cardiac-care treatment unit", "Health"),
    ("Researchers identify a gene mutation linked to a rare disorder", "Health"),
    ("Government increases funding for rural healthcare clinics", "Health"),
    ("Dengue cases climb as civic bodies intensify fogging", "Health"),
    ("Nutrition experts caution against processed-food consumption", "Health"),
    ("Health-insurance scheme expands coverage for families", "Health"),
    ("Antibiotic resistance flagged as a growing public-health threat", "Health"),
    ("Patients gain access to affordable cancer drugs under the scheme", "Health"),
    ("Nurses' union negotiates better staffing at city hospitals", "Health"),
    ("Vaccine drive extends to adolescents from Monday", "Health"),
    ("Trial reports fewer side-effects for the new therapy", "Health"),
    ("Cholera outbreak prompts a clean-water emergency", "Health"),
    ("Air pollution linked to rising asthma admissions", "Health"),
    ("Telemedicine clinic opens in the district hospital", "Health"),
    ("Nutrition drive distributes supplements to mothers", "Health"),
    ("Health officials confirm the first case this season", "Health"),
    ("Generic-drug price cut eases treatment for chronic patients", "Health"),
    ("Mental-health helpline reports a sharp call surge", "Health"),
    ("Anti-smoking drive targets educational institutions", "Health"),
    ("Organ-transplant registry crosses a record milestone", "Health"),
    ("Hospital beds fill as the viral fever spreads", "Health"),
    ("Doctors call for faster ambulance response times", "Health"),
    ("Cancer-screening camp draws thousands of visitors", "Health"),
    ("Maternal-mortality rate falls, the health survey finds", "Health"),
    ("New clinical guideline updates diabetes management", "Health"),
    ("Medical college gets permission for more seats", "Health"),
    ("Ambulance fleet upgraded with intensive-care units", "Health"),
    ("Dengue platelet count rises in the city wards", "Health"),
    ("Physiotherapy outreach serves rural patients", "Health"),
    # ---- Science ---------------------------------------------------------
    ("Space agency successfully launches a rocket carrying a satellite", "Science"),
    ("Scientists discover evidence of water on a distant planet", "Science"),
    ("ISRO's lunar mission achieves a soft landing near the south pole", "Science"),
    ("Astronomers capture an image of a distant galaxy cluster", "Science"),
    ("Researchers make a breakthrough in battery energy storage", "Science"),
    ("New species of deep-sea creature documented by marine biologists", "Science"),
    ("Physicists confirm a prediction in a landmark particle experiment", "Science"),
    ("Archaeologists uncover ancient artifacts at the excavation site", "Science"),
    ("Telescope detects signals from a far-away star system", "Science"),
    ("Genetic study traces early human migration patterns", "Science"),
    ("NASA rover sends back samples from the martian terrain", "Science"),
    ("Fusion-reactor experiment sustains a reaction for a record time", "Science"),
    ("Volcano-monitoring network predicts eruption activity", "Science"),
    ("Biologists develop a technique to edit a plant genome for yield", "Science"),
    ("Paleontologists describe a new dinosaur species from fossils", "Science"),
    ("Laboratory team publishes results from a double-blind trial", "Science"),
    ("Probe completes a gravity-assist manoeuvre past the planet", "Science"),
    ("Astronomers spot a possible exoplanet transit", "Science"),
    ("Lab achieves a higher superconducting transition temperature", "Science"),
    ("Fossil find pushes back the timeline of early mammals", "Science"),
    ("Neutrino detector records an unusual high-energy event", "Science"),
    ("Earth-observation satellite maps groundwater in the basin", "Science"),
    ("Cryogenic engine test-fire clears a launch milestone", "Science"),
    ("Gene-editing trial restores partial vision in patients", "Science"),
    ("Deep-sea submersible reaches the ocean trench floor", "Science"),
    ("Radio array picks up a distant fast radio burst", "Science"),
    ("Climate model refines the seasonal monsoon forecast", "Science"),
    ("Materials team prints a working flexible circuit", "Science"),
    ("Ancient DNA reveals an unknown human lineage", "Science"),
    ("Rocket reuses its first stage successfully", "Science"),
    ("Telescope captures a vivid planetary nebula", "Science"),
    ("Fusion reactor achieves a stable plasma pulse", "Science"),
    ("Botanists catalogue high-altitude alpine flora", "Science"),
    ("Seismograph network detects a micro-quake swarm", "Science"),
    ("Chemists propose a cheaper ammonia-production process", "Science"),
    ("Spacewalk completes the orbital station repair", "Science"),
    # ---- Entertainment ---------------------------------------------------
    ("Blockbuster film crosses a box-office record in its opening weekend", "Entertainment"),
    ("Actor wins the best-performer award at the international film festival", "Entertainment"),
    ("Streaming series renewed for a second season by popular demand", "Entertainment"),
    ("Music composer releases a chart-topping album", "Entertainment"),
    ("Bollywood star announces the next directorial venture", "Entertainment"),
    ("Celebrity couple's wedding trends across social media", "Entertainment"),
    ("Concert tour sells out arenas within hours of booking", "Entertainment"),
    ("Award ceremony honours the lifetime achievement of a veteran artist", "Entertainment"),
    ("Trailer of the upcoming movie breaks viewing records online", "Entertainment"),
    ("Singer's new single tops the music streaming charts", "Entertainment"),
    ("Film festival unveils the lineup of independent cinema selections", "Entertainment"),
    ("Director's latest release receives mixed critical reviews", "Entertainment"),
    ("Television reality-show finale draws record viewership", "Entertainment"),
    ("Pop star announces a world tour with multiple stadium dates", "Entertainment"),
    ("Classic movie is restored and re-released in cinemas", "Entertainment"),
    ("Comedian's stand-up special becomes the most-watched online", "Entertainment"),
    ("Second-part teaser tops the trending lists overnight", "Entertainment"),
    ("Indie drama sweeps the jury prizes at the festival", "Entertainment"),
    ("Remake rights acquired for the superhit film", "Entertainment"),
    ("Playback singer returns after a five-year hiatus", "Entertainment"),
    ("Web-series first-look poster unveiled online", "Entertainment"),
    ("Film crews shoot a song on a rooftop set", "Entertainment"),
    ("Late-night host mocks the awards snub", "Entertainment"),
    ("Reunion tour adds extra concert dates", "Entertainment"),
    ("Debut novel gets a screen adaptation", "Entertainment"),
    ("Casting for the ensemble finally announced", "Entertainment"),
    ("Box-office tracker declares a houseful opening week", "Entertainment"),
    ("Festival opens with a restored classic", "Entertainment"),
    ("Rapper's album breaks first-day streaming records", "Entertainment"),
    ("Award winner thanks the crew in an emotional speech", "Entertainment"),
    ("Sequel enters production with a new director", "Entertainment"),
    ("Stand-up special released on the streaming platform", "Entertainment"),
    ("Star attends the premiere in designer wear", "Entertainment"),
    ("Critic pans the overlong thriller", "Entertainment"),
    ("Drama's season finale sets a viewership record", "Entertainment"),
    ("Music-video shoot wrapped at a desert location", "Entertainment"),
    # ---- Climate ---------------------------------------------------------
    ("Climate-change summit sets new emission-reduction targets", "Climate"),
    ("Glacier retreat accelerates due to rising global temperatures", "Climate"),
    ("Cyclone makes landfall as authorities evacuate coastal areas", "Climate"),
    ("Nation pledges net-zero carbon emissions by mid-century", "Climate"),
    ("Severe drought devastates crops and hits farmers' income", "Climate"),
    ("Record heatwave prompts health alerts across the region", "Climate"),
    ("Renewable energy now accounts for a larger share of power", "Climate"),
    ("Wildfires spread rapidly amid a prolonged dry spell", "Climate"),
    ("Floods submerge villages after heavy monsoon rainfall", "Climate"),
    ("Scientists warn of accelerating biodiversity loss", "Climate"),
    ("Solar-power project commissioned to cut coal dependence", "Climate"),
    ("Melting ice sheets contribute to rising sea levels", "Climate"),
    ("Air-quality index reaches hazardous level in the capital", "Climate"),
    ("Government bans single-use plastic to protect the environment", "Climate"),
    ("Carbon-tax proposal aims to curb industrial pollution", "Climate"),
    ("Reforestation drive plants millions of saplings", "Climate"),
    ("Glacier melt threatens the downstream water supply", "Climate"),
    ("Carbon market launches with trading pilots", "Climate"),
    ("Heat action plan activated as temperatures soar", "Climate"),
    ("Mangrove restoration shields the eroding coast", "Climate"),
    ("Storm surge inundates the low-lying delta", "Climate"),
    ("Offshore wind farm now powers a million homes", "Climate"),
    ("Farmers adopt drip irrigation amid water stress", "Climate"),
    ("Melting permafrost releases methane, the study warns", "Climate"),
    ("Electric-vehicle subsidies expand to two-wheelers", "Climate"),
    ("Urban heat-island mapping guides tree planting", "Climate"),
    ("River-linking plan draws environmental objections", "Climate"),
    ("Ozone layer showing early signs of recovery", "Climate"),
    ("Wildlife corridor proposed across the hill range", "Climate"),
    ("Flood-relief camps open in the breached district", "Climate"),
    ("Plastic collectors get formal civic recognition", "Climate"),
    ("Rooftop solar installations hit a record high", "Climate"),
    ("Rainfall deficit triggers a drought declaration", "Climate"),
    ("Green-hydrogen plant commissioned at the port", "Climate"),
    ("Coral bleaching spreads along the reef system", "Climate"),
    ("City bans coal burning near schools and hospitals", "Climate"),
    # ---- Crime -----------------------------------------------------------
    ("Police arrest a suspect in the high-profile murder investigation", "Crime"),
    ("Fraud case filed against executives over the financial scam", "Crime"),
    ("Court sentences the convict in the landmark robbery case", "Crime"),
    ("Detectives recover stolen goods and seize illegal weapons", "Crime"),
    ("Kidnapping case solved within hours by the crime branch", "Crime"),
    ("Cybercrime unit probes an online financial-fraud network", "Crime"),
    ("Murder accused remanded to judicial custody by the magistrate", "Crime"),
    ("Drug-trafficking racket busted in a coordinated police raid", "Crime"),
    ("Warehouse burglary caught on a surveillance camera", "Crime"),
    ("Woman files a complaint in the assault case", "Crime"),
    ("Police question witnesses in the hit-and-run accident case", "Crime"),
    ("Money-laundering probe targets a shell-company network", "Crime"),
    ("Vehicle-theft ring arrested after a multi-city operation", "Crime"),
    ("Homicide investigation expands as new evidence surfaces", "Crime"),
    ("Scam victims gather outside the police station seeking justice", "Crime"),
    ("Smuggling gang intercepted at the port by customs officers", "Crime"),
    ("Forensic team lifts fingerprints from the van", "Crime"),
    ("Missing-person case takes a theft angle", "Crime"),
    ("Cyber cell freezes accounts in a phishing probe", "Crime"),
    ("Court grants bail to the accused businessman", "Crime"),
    ("Counterfeit-currency racket cracks in the dawn raid", "Crime"),
    ("Witness turns hostile in the assault trial", "Crime"),
    ("Stolen jewellery recovered from a fence", "Crime"),
    ("Hate-speech complaint registered under the act", "Crime"),
    ("Loan-app harassment probe nets several arrests", "Crime"),
    ("Car-jacking gang held after a pursuit", "Crime"),
    ("Cheque-bounce fraud lands an executive in jail", "Crime"),
    ("Antiquities being smuggled seized at the airport", "Crime"),
    ("Cold-case DNA match reopens the murder probe", "Crime"),
    ("Extortion note traced to a rival gang", "Crime"),
    ("Juvenile offender sent to a reform home", "Crime"),
    ("Ransom kidnapping solved by the special cell", "Crime"),
    ("Ponzi-scheme allegations surface against a firm", "Crime"),
    ("Bouncer's assault on a patron caught on CCTV", "Crime"),
    ("Smugglers' boat intercepted off the coast", "Crime"),
    ("Judge fast-tracks the sexual-assault trial", "Crime"),
    # ---- Education -------------------------------------------------------
    ("University announces the admission schedule for undergraduate courses", "Education"),
    ("Education ministry revises the school curriculum and syllabus", "Education"),
    ("College releases the merit list for first-year admissions", "Education"),
    ("National scholarship scheme opens applications for students", "Education"),
    ("New exam pattern notified for the board examinations this year", "Education"),
    ("Teacher-recruitment drive attracts a record number of applicants", "Education"),
    ("Research scholar wins a fellowship for doctoral studies abroad", "Education"),
    ("Institute launches online courses for working professionals", "Education"),
    ("Result declared for the engineering-entrance counselling round", "Education"),
    ("Vice-chancellor sworn in at the central-university convocation", "Education"),
    ("Students seek clarification on the revised grading policy", "Education"),
    ("University tops the national ranking in the annual innovation index", "Education"),
    ("Board-exam timetable released along with practical schedules", "Education"),
    ("Schools to reopen as safety certifications are granted", "Education"),
    ("Library and labs upgraded under the campus development plan", "Education"),
    ("Entrance-exam authority issues an admit-card correction window", "Education"),
    ("University admissions resume after the counsel rounds", "Education"),
    ("National entrance test to be held in two sessions", "Education"),
    ("Board publishes sample papers for the class", "Education"),
    ("Counselling rounds open for remaining seats", "Education"),
    ("University shifts to a four-year degree programme", "Education"),
    ("Scholarship disbursed to first-year students", "Education"),
    ("Anti-ragging committee conducts campus checks", "Education"),
    ("Skill-training hub inaugurated at the campus", "Education"),
    ("Study-abroad fair draws a record turnout", "Education"),
    ("Syllabus reduced for the academic year", "Education"),
    ("Hostel-fee hike sparks a students' protest", "Education"),
    ("Teacher-training intake doubles across the state", "Education"),
    ("Result-challenging window opens at the board", "Education"),
    ("Lab equipment granted to government schools", "Education"),
    ("Coding club wins the national student hackathon", "Education"),
    ("Doctoral admissions announced through an interview", "Education"),
    ("Library digitises its rare-book collection", "Education"),
    ("Internship cell partners with local firms", "Education"),
    ("Mid-day-meal scheme extended to upper primary", "Education"),
    ("Accreditation body rates the college a top grade", "Education"),
]
